version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - npm install
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 047719630077.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Build started on date
      - echo Building the Docker image...
      - docker build -t ws/assignment_test .
      - docker tag ws/assignment_test:latest 047719630077.dkr.ecr.ap-south-1.amazonaws.com/ws/assignment_test:latest
  post_build:
    commands:
      - echo Build completed on date
      - echo Pushing the Docker image...
      - docker push 047719630077.dkr.ecr.ap-south-1.amazonaws.com/ws/assignment_test:latest

artifacts:
  files:
    - imagedefinitions.json
